name: Java CI with Maven

on:
  push:
    branches: [ "main", "release" ]
    tags:
    - "v*" 
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_REPOSITORY: tallerspring-gh

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: target/taller-1.0.jar
    - name: Saves jar file
      uses: actions/upload-artifact@v4
      with:
        name: JARFILE
        path: target/taller-1.0.jar
        
  deploy-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Recovers jar file
      uses: actions/download-artifact@v4
      with:
        name: JARFILE
        path: taller-1.0.jar
    - name: Gets date for tag
      run: echo "DAYTAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USUARIO }}/${{ env.DOCKERHUB_REPOSITORY }}:250514
